version: 2
jobs:
  test:
    working_directory: ~/service
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm ci
      - run: make verify
      - run: make test-unit-coverage
      - run: make test-integration
workflows:
  version: 2
  test:
    jobs:
      - test
