name: Deploy to staging
on:
  push:
    branches:
      - master

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git push https://heroku:${{ secrets.HEROKU_AUTH_TOKEN }}@git.heroku.com/origami-image-service-qa.git $GITHUB_HEAD_REF:refs/heads/master --force --no-verify

  create-change-log:
    needs: [deploy-to-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Financial-Times/change-api-action@v1
        name: Create new change log
        with:
          change-api-key: ${{ secrets.CHANGE_API_KEY }}
          system-code: "origami-image-service-v2"
          environment: test
          slack-channels: "ft-changes,origami-deploys"

  integration-tests:
    needs: [deploy-to-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - run: npm install -g "npm@^7"
      - run: npm ci
      - run: HOST="https://origami-image-service-qa.herokuapp.com" make test-integration
