name: Deploy to dev
on: [pull_request]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to Heroku
        run: git push https://heroku:${{ secrets.HEROKU_AUTH_TOKEN }}@git.heroku.com/origami-image-service-dev.git origin/$GITHUB_HEAD_REF:refs/heads/main --force --no-verify

  create-change-log:
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Financial-Times/change-api-action@v1
        name: Create new change log
        with:
          change-api-key: ${{ secrets.CHANGE_API_KEY }}
          system-code: 'origami-image-service-v2'
          environment: dev
          slack-channels: 'ft-changes,origami-deploys'

  test:
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: git config --global url."https://${{ secrets.ORIGAMI_GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: make verify
      - run: make test-unit-coverage
        env:
          CONTENT_API_KEY: ${{ secrets.CONTENT_API_KEY }}
          CLOUDINARY_ACCOUNT_NAME: ${{ secrets.CLOUDINARY_ACCOUNT_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CUSTOM_SCHEME_STORE: ${{ secrets.CUSTOM_SCHEME_STORE }}
          API_KEY: ${{ secrets.API_KEY }}
          FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY }}
          FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}

  integration-tests:
    needs: [deploy-dev, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: HOST="https://origami-image-service-dev.herokuapp.com" make test-integration
