name: Deploy to production
on:
  release:
    types: [created]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git push https://heroku:${{ secrets.HEROKU_AUTH_TOKEN }}@git.heroku.com/origami-image-service-eu.git HEAD:refs/heads/master --force --no-verify
    - run: git push https://heroku:${{ secrets.HEROKU_AUTH_TOKEN }}@git.heroku.com/origami-image-service-us.git HEAD:refs/heads/master --force --no-verify

  create-change-log:
    needs: [deploy-to-production]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Financial-Times/change-api-action@v1
        name: Create new change log
        with:
          change-api-key: ${{ secrets.CHANGE_API_KEY }}
          system-code: "origami-image-service-v2"
          environment: prod
          slack-channels: "ft-changes,origami-deploys"
