name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: make verify
    - run: make test-unit-coverage
      env:
        CONTENT_API_KEY: ${{ secrets.CONTENT_API_KEY }}
    - run: make test-integration
      env:
        CONTENT_API_KEY: ${{ secrets.CONTENT_API_KEY }}
